[keys]
quit = ["esc"]
cancel = ["q"]
leader = ["-"]

[ui]
theme = "base16-kanagawa"

[leader.a]
help = "Show all revsets"
send = ["L", "all()", "enter"]

[custom_commands."move revision down"]
key = ["alt+j"]
args = ["rebase", "-r", "$change_id", "--insert-before", "$change_id-"]

[custom_commands."move revision up"]
key = ["alt+k"]
args = ["rebase", "-r", "$change_id", "--insert-after", "$change_id+"]
